// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversitiesApi.Db;

#nullable disable

namespace UniversitiesApi.Migrations
{
    [DbContext(typeof(UniversitiesDbContext))]
    [Migration("20240107182134_Add-Category-Enum")]
    partial class AddCategoryEnum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniversitiesApi.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Addresses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Gdańsk",
                            PostalCode = "80-233",
                            Street = "Gabriela Narutowicza 11/12"
                        },
                        new
                        {
                            Id = 2,
                            City = "Gdańsk",
                            PostalCode = "80-309",
                            Street = "Jana Bażyńskiego 8"
                        },
                        new
                        {
                            Id = 3,
                            City = "Kraków",
                            PostalCode = "30-059",
                            Street = "Mickiewicza 30"
                        });
                });

            modelBuilder.Entity("UniversitiesApi.Entities.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.ToTable("Universities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            Category = 0,
                            Description = "Politechnika Gdańska, commonly known as the Gdańsk University of Technology (PG), is a prestigious technical university located in Gdańsk, Poland. Established in 1904, PG has a rich history of providing high-quality education in engineering, technology, and science. The university is recognized for its commitment to innovation, research excellence, and fostering a collaborative learning environment.",
                            Email = "pg@pg.edu.pl",
                            Latitude = 54.219999999999999,
                            Longitude = 18.359999999999999,
                            Name = "Politechnika Gdańska",
                            PhoneNumber = "+48 123456789",
                            WebsiteUrl = "https://pg.edu.pl"
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 2,
                            Category = 1,
                            Description = "The University of Gdańsk, located in the picturesque city of Gdańsk on the Baltic coast of Poland, is a prominent academic institution known for its rich history and commitment to excellence in education and research.",
                            Email = "ug@ug.edu.pl",
                            Latitude = 54.229999999999997,
                            Longitude = 18.34,
                            Name = "Uniwersytet Gdański",
                            PhoneNumber = "+48 94354599",
                            WebsiteUrl = "https://ug.edu.pl"
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 3,
                            Category = 0,
                            Description = "AGH University of Science and Technology, located in the historic city of Kraków, Poland, is a prestigious academic institution celebrated for its strong focus on science, engineering, and technology. Established in 1919, AGH has a storied history of providing high-quality education and conducting cutting-edge research.",
                            Email = "agh@agh.edu.pl",
                            Latitude = 54.030000000000001,
                            Longitude = 19.550000000000001,
                            Name = "AGH",
                            PhoneNumber = "+48 953443553",
                            WebsiteUrl = "https://www.agh.edu.pl"
                        });
                });

            modelBuilder.Entity("UniversitiesApi.Entities.University", b =>
                {
                    b.HasOne("UniversitiesApi.Entities.Address", "Address")
                        .WithOne("University")
                        .HasForeignKey("UniversitiesApi.Entities.University", "AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("UniversitiesApi.Entities.Address", b =>
                {
                    b.Navigation("University")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
